Homework1: Andrey Senko
Shurke/pt1-47-22 pull request #10
Opened 2022-02-09 19:36 UTC by m4noon

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-02-13 13:46 UTC, Shurke requested changes
Обратите внимание на ввод и вывод в ваших скриптах. Будет здорово, если вы в будущем будете писать более понятные приглашения и комментарии к выводу.

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task1.py
> +    sum_cents -= 100
Для нахождения количества рублей и количества копеек стоит воспользоваться целочисленным делением и нахождением остатка от деления.

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task1.py
> +print('Сумма за', count, 'товара составила:', sum_rubles, 'рублей и', sum_cents, 'копеек')
Для форматирования ответа лучше использовать строковый метод `format` или f-строки.

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task2.py
> +signs = [';', ',', '.', ':', '!', '?']
В модуле `string` имеется константа, которая хранит в себе знаки препинания.

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task2.py
> +print(max(string.split(), key=len))
Было бы здорово добавлять пояснения к тому, что выводится на экран.
Например
```py
print(f'Самое длинное слово в введенном предложении - {max(string.split(), key=len)}')
```

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task3.py
> +print(new_string.strip())
См. замечание про вывод.

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task3.py
> +    if char not in new_string:
При таком подходе будут добавляться пробелы в результирующую строку, чего не должно быть.

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task4.py
> +    elif char == string[index].lower():
Здесь так же будут учтены буквы другого алфавита, не только английского.
Из условия:

> Учитывать только английские буквы.

2022-02-13 13:46 UTC, Shurke commented on src/homework1/task4.py
> +index = 0
Переменная `index` существует только для того, чтобы существовать и не выполняет никакой смысловой нагрузки в коде.

2022-02-18 14:41 UTC, m4noon commented on src/homework1/task3.py
> +    if char not in new_string:
Я подумал над этим и при объявлении new_string  добавил пробел, то есть new_string = '  '. Так пробелы не войдут в результирующую строку, а пробел в начале я удаляю методом .strip(). Надеюсь я правильно вас понял.

2022-02-18 14:49 UTC, m4noon commented on src/homework1/task4.py
> +index = 0
index я использовал в 14 и 16 строке кода:
```
for char in string:
    if char == string[index].upper():
        count_high += 1
    elif char == string[index].lower():
        count_low += 1
    index += 1
```

2022-02-21 18:12 UTC, Shurke commented on src/homework1/task3.py
> +    if char not in new_string:
Да, вы придумали вполне рабочий вариант.)
Но можно было бы просто добавить еще проверку `char != ' '` и тогда не пришлось бы хитрить.)

2022-02-21 18:12 UTC, Shurke commented on src/homework1/task5.py
> +print('n-ое число Фибаначи:', sum)
При этом в предыдущей задаче вы формировали ответ через f-строку.

2022-02-21 18:12 UTC, Shurke commented on src/homework1/task7.py
> +    print('Площаь треугольника S =', s)
Такое же замечание про f-строку.

2022-02-21 18:13 UTC, Shurke commented
Итоговая оценка - 8.5.

2022-02-21 18:13 UTC, closed without merging