Homework1: Kiryl Strunets
Shurke/pt1-47-22 pull request #14
Opened 2022-02-10 11:59 UTC by Kir3103

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-02-13 17:19 UTC, Shurke requested changes
Стоит обратить внимание и поработать над именованием переменных, т.к. переменные стиле одной буквы не несут информации о том, что в них хранится и для чего они нужны.

2022-02-13 17:19 UTC, Shurke commented on src/task1.py
> +print('Общая стоимость:', price // 100, 'рублей', price % 100, 'копеек')
Для форматирования ответа лучше использовать строковый метод `format` или f-строки.

2022-02-13 17:19 UTC, Shurke commented on src/task2.py
> +    if len(i) > W1:
В решении не учитывается наличии знаков препинания.

2022-02-13 17:19 UTC, Shurke commented on src/task8.py
> +PROBLEM = 1  # pylint W0105
Для чего нужна данная константа?

2022-02-13 17:19 UTC, Shurke commented on src/task8.py
> +    print('Байкер находится на отметке:', MARK)
Вызов функции `print` можно оставить только один, переместив на последнюю строку скрипта.

2022-02-13 18:24 UTC, Kir3103 commented on src/task8.py
> +PROBLEM = 1  # pylint W0105
> Для чего нужна открытая константа?

Без этой переменной pylint не пропускал мой файл. Он выдавал ошибку по строкам, в которых начинались условия задач. Перепробовал все и помогло только такое решение с переменной, которое нашел в интернете.

2022-02-23 16:38 UTC, Shurke reviewed
Именование переменных хромает на обе ноги.

2022-02-23 16:38 UTC, Shurke commented on src/task2.py
> +print(max(WORD_LIST, key=len))
Стоило бы добавить пояснение к тому, что выводится на экран.

2022-02-23 16:38 UTC, Shurke commented on src/task8.py
> +        S_NEW = S_NEW + str_[i]
В таком случае можно использовать оператор `+=`
```py
S_NEW += str_[i]
```

2022-02-23 16:38 UTC, Shurke commented
Итоговая оценка - 8.

2022-02-23 16:38 UTC, closed without merging