Homework1:BakacheusriDmitry
Shurke/pt1-47-22 pull request #18
Opened 2022-02-10 18:42 UTC by DmitryBakacheuski

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-02-11 19:11 UTC, DmitryBakacheuski commented
я не могу найти где flake8 видит ошибку, Pycharm ничего не подсвечивает и сам я лишних пробельных символов не нашел

2022-02-13 17:48 UTC, Shurke commented
1. В данной PR содержатся решения 1-й и 2-й домашней работы. Пожалуйста, оставьте в этом PR решения для 1-й домашней работы и откройте PR для 2-й.

2. > я не могу найти где flake8 видит ошибку, Pycharm ничего не подсвечивает и сам я лишних пробельных символов не нашел

У вас в некоторых файлах (к примеру `src/Homework2/task4.py`) не хватает пустой строки в конце файла, что flake8 засчитывает как ошибку. Кроме того, у вас в конце некоторых строк весят пробелы, которых не должно быть. Обратите внимание на 60-ю строку.
![Screenshot 2022-02-13 at 20 47 56](https://user-images.githubusercontent.com/44495358/153767697-2ce54fe7-21be-4740-8041-1378883ad6f4.png)

2022-02-14 20:14 UTC, DmitryBakacheuski commented
C пробелами разобрался, но вот последняя  пустая строка удаляется автоматически во время создания коммита или при любых действиях не в Pycharm .

2022-02-16 18:53 UTC, Shurke requested changes
1. Будет здорово, если вы будете добавлять понятные приглашения к вводу данных с клавиатуры и пояснения к тому, что выводится на экран в результате работы скрипта.
2. Стоит обратить внимание и поработать над именованием переменных, т.к. переменные стиле одной буквы не несут информации о том, что в них хранится и для чего они нужны.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task1.py
> +L = int(input())
Стоит добавлять понятные приглашения к вводу, чтобы пользователь понимал, что от него ожидается.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task1.py
> +print({'Общая цена'}, a // 100, {'рублей'}, a % 100, {'копеек'})
Для формирования ответа стоит воспользоваться либо строковым методом `format` или f-строкой.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task3.py
> +print(b)
Пропущена пустая строка в конце модуля.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task4.py
> +        lower += 1
> Учитывать только английские буквы.

Не учтено.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task5.py
> +print(c)
Пропущена пустая строка в конце модуля.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task4.py
> +print('Прописных: ', upper, 'Строчных: ', lower)
Пропущена пустая строка в конце модуля.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task6.py
> +    print("Не палиндром")
Пропущена пустая строка в конце модуля.

2022-02-16 18:53 UTC, Shurke commented on src/homework1/task7.py
> +    print("Неверные данные")
Пропущена пустая строка в конце модуля.

2022-02-18 13:50 UTC, Shurke requested changes
Замечание с именами переменных остается актуальным.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task2.py
> +a = input().translate(str.maketrans('', '', string.punctuation)).split(' ')
Нет приглашения ко вводу.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task2.py
> +print(c)
Нет пояснения к тому, что выводится на экран.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task3.py
> +print(b)
Нет пояснения к тому, что выводится на экран.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task5.py
> +n = int(input())
Нет приглашения ко вводу.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task5.py
> +print(c)
Нет пояснения к тому, что выводится на экран.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task6.py
> +a = int(input())
Нет приглашения ко вводу.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task4.py
> +print('Прописных: ', upper, 'Строчных: ', lower)
Для формирования строки для вывода стоит использовать либо строковый метод `format`, либо f-строку.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task7.py
> +c = float(input())
Нет приглашения к вводу.

2022-02-18 13:50 UTC, Shurke commented on src/homework1/task8.py
> +    return n * n * n
Вы уверены, что написанный код решает задачу? Потому что я вижу вычисление куба числа, а не суммирование чисел в строке.

2022-02-19 11:28 UTC, DmitryBakacheuski commented on src/homework1/task8.py
> +    return n * n * n
Куб номера строки равен сумме числе в этой строке ( по крайней в этом частном случае )

2022-02-21 18:19 UTC, Shurke reviewed
Замечание про использование f-строк применено не ко всем задачам.

2022-02-21 18:19 UTC, Shurke commented on src/homework1/task8.py
> +    return n * n * n
Принято.

2022-02-21 18:20 UTC, Shurke commented
Итоговая оценка - 8.

2022-02-21 18:20 UTC, closed without merging