Homework1: Vladislav Nagorny
Shurke/pt1-47-22 pull request #19
Opened 2022-02-10 19:57 UTC by VladislavNagorny

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-02-13 17:51 UTC, Shurke requested changes
1. На лекции обращалось внимание, что во все файлы с решением задач должны быть добавлены условия в виде строки документации.
2. Во всех файлах отсутствует пустая строка в конце.
3. Будет здорово, если вы будете добавлять понятные приглашения к вводу данных с клавиатуры и пояснения к тому, что выводится на экран в результате работы скрипта.

2022-02-13 17:51 UTC, Shurke commented on src/task1.py
> +print('Общая цена ' + str(total // 100) + ' рублей ' + str(total % 100) + ' копеек')
Для форматирования ответа лучше использовать строковый метод `format` или f-строки.

2022-02-13 17:51 UTC, Shurke commented on src/task4.py
> +print("Small letters " + str(small_letters))
Решение правильное, но сильно сложное для такой простой задачи.

2022-02-21 17:24 UTC, VladislavNagorny reviewed
comments reviewed

2024-07-03 21:24 UTC, closed without merging