Homework2:Bakacheuski Dmitry
Shurke/pt1-47-22 pull request #23
Opened 2022-02-14 20:18 UTC by DmitryBakacheuski

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-02-21 19:26 UTC, Shurke requested changes

2022-02-21 19:26 UTC, Shurke commented on .gitignore
> +src/homework1/
Файлы первой домашней работы можно просто удалить соотвествующей ветки. И тогда не нужно будет изменять `.gitignore`.

2022-02-21 19:26 UTC, Shurke commented on src/Homework2/task10.py
> +print('Итог: ' + ', '.join(map(str, list_2)))
Код не работает.
<img width="1081" alt="Screenshot 2022-02-21 at 22 08 23" src="https://user-images.githubusercontent.com/44495358/155014000-4feae842-b460-4601-8a76-74dcae6a3bda.png">

2022-02-21 19:26 UTC, Shurke commented on src/Homework2/task3.py
> +tuple_1 = tuple(list_1)
Можно ведь проще.
```py
tuple_1 = ('123',)
```

2022-02-21 19:26 UTC, Shurke commented on src/Homework2/task6.py
> +list_3 = []
Стоит подумать над тем, чтобы дать переменным более понятные имена:
```py
list_negative = []
list_zero = []
list_positive = []
```

2022-02-21 19:26 UTC, Shurke commented on src/Homework2/task7.py
> +print('Счастливые числа: ' + ', '.join(map(str, list_1)))
> Убедитесь в том, что среди этих чисел не будет дубликатов.

Не выполнено условие.

2022-02-21 19:26 UTC, Shurke commented on src/Homework2/task8.py
> +    print(False)
Стоит добавить пояснение к выводу.

2022-02-22 18:58 UTC, DmitryBakacheuski commented on src/Homework2/task7.py
> +print('Счастливые числа: ' + ', '.join(map(str, list_1)))
Немного поправил ошибки которые увидел. Не понимаю откуда могут взяться дубликаты если в 10 строке генерируется список из 50 разных цифр, в 11 меняется порядок, а в 12 просто берутся первые 6 из них.

2022-02-27 11:44 UTC, Shurke commented on .gitignore
> +src/homework1/
Замечание не устранено.

2022-02-27 11:44 UTC, Shurke commented on src/Homework2/task2.py
> +import copy
Импорт идет после строки документации.

2022-02-27 11:44 UTC, Shurke commented on src/Homework2/task7.py
> +list_1 = sorted(list_1[:6])
> Убедитесь в том, что среди этих чисел не будет дубликатов.

Не выполнено.

2022-02-27 11:45 UTC, Shurke commented
Итоговая оценка - 8.

2022-02-27 11:45 UTC, closed without merging