Homework1: Artem Molchanov
Shurke/pt1-47-22 pull request #3
Opened 2022-02-07 12:16 UTC by Kissloroid

HW1 in progress

2022-02-11 16:35 UTC, Shurke requested changes

2022-02-11 16:35 UTC, Shurke commented on src/homework1/task1.py
> +print('Общая стоимость составит ' + str(result_rub) + ' рублей ' + str(result_pound) + ' копеек')
Стоит пользоваться или f-строкой или методом `formart` для формирования ответа.

2022-02-11 16:35 UTC, Shurke commented on src/homework1/task2.py
> +    sentence = sentence.replace(punctuation[i], " ")  # a list of punctuation characters
Я не вижу препятствий, чтобы не итерироваться сразу по строке со знаками препинания.
```py
for i in punctuation:                     
    sentence = sentence.replace(i, " ")
```

2022-02-11 16:35 UTC, Shurke commented on src/homework1/task3.py
> +        res.append(i)                            # add to new list
Либо, можно сразу же работать со строкой.

2022-02-11 16:35 UTC, Shurke commented on src/homework1/task4.py
> +        uppercase += 1                                          #
В модуле `string` есть константы, которые хранят заглавные и строчные символы английского алфавита.

2022-02-11 16:35 UTC, Shurke commented on src/homework1/task4.py
> +    #     print(str(x) + ' - не является английским символом')  # an unsuitable char as a result
Если код закомментирован, значит он не нужен в итоговом решении.

2022-02-11 16:35 UTC, Shurke commented on src/homework1/task8.py
> +"""
Почему решения закомментированы?

2022-02-13 20:22 UTC, Kissloroid commented on src/homework1/task8.py
> +"""
Коvментировал для проверки кода в PyCharm.

2022-02-16 19:07 UTC, Shurke reviewed
Стоит продолжить работу над именами переменных. Уходите от именования в стиле одной буквы.

2022-02-16 19:07 UTC, Shurke commented on src/homework1/task2.py
> +        wrd = c
Как вариант, можно было воспользоваться функцией `max()`.

2022-02-16 19:07 UTC, Shurke commented on src/homework1/task3.py
> +print(res)
Стоило бы добавить пояснение к тому, что выводится на экран.

2022-02-16 19:07 UTC, Shurke commented
Итоговая отметка - 8.

2022-02-16 19:07 UTC, closed without merging