Homework3: Molchanov Artem
Shurke/pt1-47-22 pull request #52
Opened 2022-02-24 11:39 UTC by Kissloroid

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-02-28 20:20 UTC, Shurke requested changes

2022-02-28 20:20 UTC, Shurke commented on src/homework3/task01.py
> +dict = {x: x**3 for x in range(1, 20)}
1. Стоит избегать использование зарезервированных слов языка для именования переменных. 
2. Математические операции отделяются с двух сторон пробелами.
```py
dict = {x: x ** 3 for x in range(1, 20)}
```
3. В итоговом ответе не будет ключа `20` и соответствующего ему значения в кубе.

2022-02-28 20:20 UTC, Shurke commented on src/homework3/task05.py
> +            output.append(str(digit) * (symbol.index(char) + 1))
Для чего здесь переводить число в строковое представление, если можно сразу задать ключ в строковом формате?

2022-02-28 20:20 UTC, Shurke commented on src/homework3/task08.py
> +print(f'Итоговое множество: {set_get(digit_list)}')
Программа не работает согласно условию.
<img width="1135" alt="Screenshot 2022-02-28 at 23 17 32" src="https://user-images.githubusercontent.com/44495358/156052571-f87dc29e-0399-42e5-8b20-479ee558feeb.png">

2022-02-28 20:20 UTC, Shurke commented on src/homework3/task09.py
> +both = len(set(range(1, 14)))
Подписки стоило бы вынести в отдельные переменные.

2022-03-02 10:22 UTC, Kissloroid commented on src/homework3/task08.py
> +print(f'Итоговое множество: {set_get(digit_list)}')
Моя вина, неверно условия задачи понял.

2022-03-12 06:33 UTC, Shurke commented
Итоговая оценка - 8.5.

2022-03-12 06:33 UTC, closed without merging