Homework3: Tatsiana Sauko
Shurke/pt1-47-22 pull request #55
Opened 2022-02-26 13:56 UTC by TatsianaSauko

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-02-28 20:35 UTC, Shurke requested changes

2022-02-28 20:35 UTC, Shurke commented on src/homework3/task2.py
> +for i in range(0, number_of_countries):
Когда генерируется значение от нуля, то не обязательно писать 0.
Т.е. `range(number_of_countries)` будет более питонистическим вариантом.

2022-02-28 20:35 UTC, Shurke commented on src/homework3/task9.py
> +new_jour = {int(item) for item in range(1, 14)}
Количество подписок стоило бы вынести в переменные.

2022-02-28 20:35 UTC, Shurke commented on src/homework3/task2.py
> +for elem in range(0, number_of_cities):
Тоже самое, что и чуть выше в замечании.

2022-02-28 20:35 UTC, Shurke commented on src/homework3/task5.py
> +            output.append(str(key) * (value.index(elem) + 1))
Для чего было задавать ключи словаря целочисленными значениями, если потом переводите в строковые значения?

2022-02-28 20:35 UTC, Shurke commented on src/homework3/task8.py
> +lst_1 = [int(item) for item in input("Введите числа ч/з пробел: ").split()]
А для чего и здесь осуществляется перевод в целочисленное значение, а потом повторяющиеся значения переводить обратно в строковые значения?

2022-03-01 08:57 UTC, TatsianaSauko commented on src/homework3/task8.py
> +lst_1 = [int(item) for item in input("Введите числа ч/з пробел: ").split()]
У нас же в 8-ой задаче нужно вывести множество, например, если число 4 повторяется 3 раза, то в множестве будет следующая запись: само число 4, строка "44", строка "444" ({4,  "44", "444"}). Поэтому я сразу в множество добавляю целое число, которое было при выводе, а затем, если их больше одного преобразовываю в тип str.

2022-03-12 06:29 UTC, Shurke commented
Итоговая оценка - 8.

2022-03-12 06:29 UTC, closed without merging