Homework4: Yanushkevich Vladislav
Shurke/pt1-47-22 pull request #60
Opened 2022-03-19 21:43 UTC by Jenderlion

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-03-20 11:02 UTC, Shurke requested changes

2022-03-20 11:02 UTC, Shurke commented on .gitignore
> +src/homework4/*.zip
Данные файлы можно было просто не добавлять в коммит и тогда не надо было бы их игнорировать.)

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task1.py
> +                pass
Данный кусок кода решает задачу, что если файла нет, то создать его. Но задача решена с оверхедом. 
В Python есть либа `os` и там можно найти функцию `os.path.exists()` которая проверяет наличие файла.
Подробнее можно почитать в [статье](https://www.pythontutorial.net/python-basics/python-check-if-file-exists/).
Таким образом задача сведется к тому, что проверили файл и принимаем решение о том, как файл открывать.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task10.py
> +        words_native = opened_file.readlines()
Данное решение несколько не удачно по использованию памяти. Сейчас вычитан просто весь файл. И потом ведется с ним работа. 
Более оптимальным вариантом будет в цикле читать строку за строкой и обрабатывать полученные данные.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task10.py
> +            words.append(elem[:-1])
А тут создается копия вычитанного файла.
Если посмотреть на код, то вся работа идет внутри контекстного менеджера. Т.е. у нас уже есть весь файл в `words_native` и еще создается копия в `words`.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task10.py
> +                print(word)
Как вариант, можно использовать словарь, где ключи - это длины слов, а значение - списки слов. 
Думаю, что такая структура хранения данных упростит само решение и снизит потребление памяти.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task11.py
> +def get_year_dict(period=None):
Функцию `get_year_dict` можно и нужно разбить на несколько функций поменьше.
Основная идея такого разбиения - это то, что функция должна выполнять какое-то одно законченное действие:
- прочитать данные из файла
- обработать сырые данные и подготовить словарь (или словари) с данными по годам
- найти популярное имя 
- и т.д.

Кроме того, к функциям **нужно** писать строки документации. Опционально - использование тайпинга.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task11.py
> +                result[str(i)] = years_dict[str(i)]
Сейчас нет большой разницы в том, был введен какой-то конкретный год или нет. 
В каждом разе программа будет вычитывать все данные, подготавливать их и потом выводить на экран.
В идеале, программа должна работать только с файлами конкретного года (годов).

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task11.py
> +    for key, value in name_dict.items():
`key` и `value` не дают ни малейшего понятия о том, что обрабатывается в данный момент.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task11.py
> +        print('In my opinion you made a mistake.')
Если модуль импортировать, то код в любом случае будет выполнен. 
Для избежания это стоит ознакомиться со [статьей](https://www.freecodecamp.org/news/if-name-main-python-example/#:~:text=We%20can%20use%20an%20if,name%20if%20it%20is%20imported.).

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task11.py
> +            for name, num in name_dict.items():
Я насчитал 3 цикла. Сложность решения просто в космос улетела.)

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task11.py
> +def print_popular_name(input_dict):
Имя функции говорит о том, что будет печать на экран. При этом, тут есть еще подготовка данных. 
Т.е. функция делает 2 действия.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task11.py
> +            for name in name_dict.keys():
Снова 3 цикла.)

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task12.py
> +    elif roman_num[:2] in pairs.keys():
Оператор `in` по умолчанию работает с ключами словаря и нет необходимости явно вызывать метод `keys()`.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task12.py
> +for num in ['XCVII', 'CXLVIII', 'CLXXXVIII', 'MCMDCCXLIV']:
> Также напишите основную программу, которая будет запрашивать у пользователя число, введенное римскими цифрами...

Не реализовано.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task13.py
> +        seq = get_sequence()
Вот каким образом из данной строки, без перехода в функцию, можно понять, что тут происходит получение символов химических элементов?

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task13.py
> +while True:
Если используется бесконечный цикл, то для пользователя должен быть предоставлен понятный способ выхода их программы. 
Например, `для выхода из программы введите exit()`.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task13.py
> +def get_sequence():
Имя функции ничего не говорит о том, что программа делает. 
Кроме того, результат работы функции - это словарь, который к `sequence` не имеет отношения от слова совсем.)

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task13.py
> +        seq = get_sequence()
Стоит сделать тогда уже возможность по вводу `help` получение информации о программе: что делает, какие опции можно ввести с клавиатуры и какие действия будут, как выйти из программы и т.д.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task13.py
> +def word_with_elem(word, sequence):
Думаю, что если пересмотреть подход к хранению данных из таблицы элементов, то решение будет проще.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task14.py
> +def decorator_with_limit(func, limit=10):
Тут должен быть декоратор с параметром. И он пишется совсем не так.) Стоит пересмотреть лекцию или прочесть [статью](https://realpython.com/primer-on-python-decorators/).

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task14.py
> +            raise BufferError('TooManyErrors')
Можно просто создать кастомное исключение.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task3.py
> +def binary_pyramid(m=1, n=4):
А может все же позволить пользователю вводить данные?)

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task2.py
> +    result_list = []
Вот если читать имя переменной, то ожидается, что тут будет результат работы функции. Хотя, это всего лишь промежуточная переменная и итоговые данные из которых собирается строка ответа - это `range_list`.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task4.py
> +for i in [10, 20, 1, 13]:
Тот же вопрос про ввод данных пользователем.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task6.py
> +    print(f'Стоимость поездки: {(num_of_points * 0.25) + 4} BYN')
Данные числа являются константами. И логично, что их стоит поместить в переменные. Так будет проще поддерживать возможные изменения в коде.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task6.py
> +    trip = input('Пожалуйста, укажите протяжённость поездки: ')
И как пользователь должен понять, что от него ожидают ввод расстояния в виде `4.2 км`?

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task7.py
> +        except Exception:
Если обрабатывается исключение, то конкретное исключение должно быть обработано. А не ловить все подряд.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task7.py
> +        return day.strftime('%j')
Функцию стоит вынести до 20-й строки. 
Потому что в таком случае, не будет возможности импортировать данный модуль и воспользоваться функцией в другом модуле.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task8.py
> +        return password
См. замечание выше про импорт.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task9.py
> +    general_tea = (tea + table * 3 + cup * 16 * 3) * factor
Все данные должны быть вынесены в константу. Так будет проще поддерживать код, изменяя числа только в одном месте.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task9.py
> +def cooking(cup=1, table=2, tea=8, factor=7):
> Функция должна принимать в качестве параметра `количество единиц измерения`, а также `их тип` (стакан, столовая или чайная ложка).

Ожидается, что вызов функции будет выглядеть `cooking(59, 'teaspoons')`, а на выходе - `1 cup, 3 tablespoons, 2 teaspoons`.
Следовательно, стоит у пользователя спрашивать количество и тип единицы измерения.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task_with_star.py
> +                truth_list.append(0)
Вместо огромной простыни из `if ... elif ... else ...` каждую логическую функцию имеет смысл вынести в отдельную функцию. [Пример](https://stackoverflow.com/questions/21962763/using-a-dictionary-as-a-switch-statement-in-python), как это можно реализовать. 
Далее создать словарь, в который поместить имя функции и сам объект функции. Когда пользователь введет имя функции, то из словаря получить функцию и вызвать ее с тем количеством атрибутов, которое пришло на вход.

2022-03-20 11:02 UTC, Shurke commented on src/homework4/task_with_star.py
> +def get_array(list_of_variables):
`get_array` вообще не говорит ничего о том, что делает функция. С таким же темпом, функция может просто пустой список отдавать и на этом все. А на самом деле, идет генерация каких-то значений.

2022-03-27 09:00 UTC, Shurke requested changes

2022-03-27 09:00 UTC, Shurke commented on .gitignore
> +src/homework4/*.zip
Все также актуально.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task1.py
> +        if os.path.exists('res_of_functions.txt') is False:
Для чего нужна проверка `is False`, если можно проверить следующим образом
```py
if os.path.exists('res_of_functions.txt'):
```

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task1.py
> +
Для чего нужны пробельные строки?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task1.py
> +    """Logging wrapper"""
Строка документации должна говорить о том, что результаты пишутся в файл для каждого вызова функции, которая будет задекорирована. 
Как собственно и имя декоратора должно говорить об этом. Сейчас ожидается, что будет отдан какой-то список результатов.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task1.py
> +        import os
Импорт осуществляется на глобальном уровне вначале модуля.
Смотри [РЕР 8](https://peps.python.org/pep-0008/#imports)

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task10.py
> +            words.append(string[:-1])
1. `words`  стоит объявить до контекстного менеджера.
2. Не обязательно читать строку, а потом в цикле продолжать это делать. 
```py
while True:
    line = opened_file.readline()
    if not line:
        break
    words.append(line[:-1])
```

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task10.py
> +            words_len[len(word)].update({word, })
А чем не устроил метод `add`?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +    import zipfile
Импорт осуществляется вначале модуля, после строки документации.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +        date_list = tuple(range(1800, 2051))
Почему создается такой большой кортеж? В условии идет промежуток с 1900 по 2012 года. 

> 1900-го и заканчивая 2012-м

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +        date_list = tuple(range(int(period[:4]), int(period[5:]) + 1))
1. Можно сделать `split` и использовать в качестве разделителя `-`. 
2. Для повышения читаемости, стоит начало и конец периода вынести в переменные.
```py
start_date = int(period[:4])
end_date = int(period[5:])
date_list = tuple(range(start_date, end_date + 1))
```
Строчки кода бесплатные, а читаемость кода возрастает в разы.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +    """Print search period and return dict with data for period or False"""
Я уже делал это замечание и делаю его еще раз. 
Функция должна выполнять одно действие. 
В данном случае получается три:
1. Выделение временного интервала из входной строки. 
2. Печать временного промежутка.
3. Процессинг данных и получение словаря для дальнейшей работы. 
Так что 1-й и 3-й пункт должны быть разнесены в отдельные функции. 2-й пункт можно сделать простой строчкой в теле основной программы.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +    while True:
Теперь еще осталось почитать про то, как тело основной программы помещают в функцию `main()`.)
И в целом вызов получается вполне изящный.
```py
if __name__ == '__main__':
    main()
```
Данное замечание распространяется на все остальные файлы.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +    """Print lists with most popular (top 10) names"""
См. замечание выше про организацию функций.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +    """Print lists with generic names"""
См. замечание выше про организацию функций.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +        import heapq
Импорт!!!

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task11.py
> +                b_name_set.update({name})
Тот же вопрос про `add`, что и выше.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task12.py
> +    """
Не вижу ни одной инструкции `try` в теле функци. Следовательно, стоит писать о том, что осуществляется перевод. 
[РЕР 257](https://peps.python.org/pep-0257/) рассказывает о том, как писать строки документации.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task12.py
> +def get_arabian(roman_num: str) -> int:
Если уж использовать type hints, то стоит это делать во всей домашке, а не только в отдельном файле.)

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task13.py
> +        elements_native.clear()
Как только программа закончит свою работу и выйдет из тела функции, все локальные переменные данной функции будут и так удалены.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task13.py
> +def get_sequence_dict_from_file(file_name='elements.txt') -> dict:
Так последовательность или словарь?
`get_chem_elements` - как пример имени функции. Структура возвращаемых данных описывается в строке документации функции.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task13.py
> +def word_with_elem(word: str, sequence: list) -> str:
Для чего столько пустых строк в теле функции?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task14.py
> +class CustomError(Exception):
> TooManyErrors

В условии четко указано имя кастомного исключения.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task14.py
> +            while exit_flag is False and num_of_try < limit:
Более лаконичная и правильная запись
```py
while not exit_flag and num_of_try < limit:
```
Кроме того, `is False` имеет место быть, но только в определенных случаях. В большинстве своем стоит все же использовать `== False`. Про разницу подходов можно прочесть в [статье](https://stackoverflow.com/questions/16513573/if-var-false)

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task14.py
> +                    num_of_try += 1
Для чего здесь данный блок?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task2.py
> +    result_list = []
Замечание осталось не исправленным.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task2.py
> +    return result
Опять же вопрос, зачем тут пустые строки?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task3.py
> +                m_int, n_int = int(m__and_n[0]), int(m__and_n[1])
Стоит добавить проверку входных данных, чем ловить исключения.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task4.py
> +def nearest_degree(inp_num=9) -> str:
Почему аннотация типов сделана только частично?
В коде есть подобные места.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task5.py
> +    print(nearest_divisor(i))
> Вводится число

Где?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task6.py
> +    import math
Импорт!!!

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task6.py
> +            print('Пожалуйста, укажите число!')
Лучше сделать проверку входных данных, чем ловить исключение.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task7.py
> +    import datetime
Импорт!!!

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task7.py
> +            print('А теперь попробуйте ввести 3 числа.')
См. замечание выше про проверку входных данных.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task8.py
> +        import random
Импорт!!!

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task8.py
> +    def get_password():
Функция должна быть вынесена на уровень модуля. 
Если сейчас импортировать модуль, то `get_password` будет не доступна к использованию.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task9.py
> +    number = int(input('What quantity? '))
В условии есть же пример 

> 59 чайным ложкам

Следовательно стоит ориентироваться на него. 
```py
container = input('Please enter data for conversion. Example - 59 teaspoons')
```

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task_with_star.py
> +                     'XNOR': xnor_func(value_array), 'XOR': xor_func(value_array)}
Такие конструкции (это могут быть и списки, и кортежи), которые занимают несколько строк, лучше писать в следующем стиле
```py
func_dict = {
    'AND': and_func(value_array),
    'OR': or_func(value_array),
    'NAND': nand_func(value_array),
    'NOR': nor_func(value_array),
    'XNOR': xnor_func(value_array),
    'XOR': xor_func(value_array),
}
```
Расположение каждого элемента в новой строке позволит легко отслеживать изменения в системах контроля версий. Будет четко видно, что было добавлено или изменено.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task9.py
> +while True:
Почему здесь не применена конструкция `if __name__ == "__main__":`?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task_with_star.py
> +        print(get_table(example_func))
Почему здесь не применена конструкция `if __name__ == "__main__":`?

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task_with_star.py
> +def get_table(func='AND', seq=('A', 'B')) -> str:
Эту функцию стоит декомпозировать. 
Тут и составление словаря, и вычисление результатов работы всей программы. 
Отдельные логические функции стоит вынести на уровень модуля. Словарь с стоит сделать константой на уровне модуля. 
А здесь уже оставить вычисление результата работы программы.

2022-03-27 09:00 UTC, Shurke commented on src/homework4/task_with_star.py
> +    user_seq = input('Type the variables separated by space: ').split()
> some_func("AND", A, B)

В условии четко прописан формат ввода. Почему он не соблюден?

2022-04-03 18:05 UTC, Jenderlion commented on src/homework4/task14.py
> +                    num_of_try += 1
Считает количество попыток выполнить функцию - на тот случай, если функция всё же выполнится.

2022-04-03 19:04 UTC, Jenderlion commented on src/homework4/task_with_star.py
> +        print(get_table(example_func))
Потому что условием не поставлена эта задача. Оберну при следующем pr

2022-05-03 13:13 UTC, Shurke reviewed
Строки документации остались неравномерными по всей домашней работе. В каких-то задачах есть перечень того, что функция принимает, что нет. Где-то в задаче есть аннотация типов, где-то нет. 

Итоговая оценка - 9.

2022-05-03 13:13 UTC, Shurke commented on src/homework4/task1.py
> +    :param func: *args and **kwargs for func
В функции `write_log_of_result` нет атрибутов `*args and **kwargs`.
Здесь стоило писать только про `func`.

2022-05-03 13:13 UTC, Shurke commented on src/homework4/task1.py
> +    def wrapper(*args, **kwargs):
Почему в `wrapper` нет строки документации?)

2022-05-03 13:13 UTC, Shurke commented on src/rss_reader/rss reader.md
> +# Introduction to Python. Final task.
Этот файл не относится к домашней работе  №4.

2022-05-03 13:14 UTC, closed without merging

2022-05-03 15:04 UTC, Shurke commented on src/homework4/task14.py
> +            return result
1. В условии не указан тип исключения, который должен быть перехвачен.
2. `возникло какое-то исключение, то функция должна перезапуститься еще раз.` - не реализовано.
3. При таком подходе, новая задекорированная функция сотрет результаты текущего декоратора.