Homework4: Kiryl Strunets
Shurke/pt1-47-22 pull request #65
Opened 2022-04-26 15:10 UTC by Kir3103

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-05-03 15:13 UTC, Shurke requested changes

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task10.py
> +        open_file = user_file.read().split()
В `open_file` все же содержится не файловый дескриптор открытого файла, а вычитанные данные.
Следовательно, имя переменной должно быть соответствующим.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task10.py
> +                    all_longest_word.remove(words)
Если изменить подход к хранению данных, то задачу можно решить в один проход по вычитанным словам.
А можно вообще без цикла решить. :)

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task11.py
> +                boys_years_dict[years] = boys_dict
Точно такой же фрагмент кода выполняется при получении девичьих имен. Следовательно, можно вынести в отдельную функцию.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task11.py
> +            b_unique_set.add(b_name)
А для чего тут необходим перебор каждого имени?
`keys()` возвращает все ключи словаря, которые можно сразу добавить в множество `b_unique_set`.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task11.py
> +            g_unique_set.add(g_name)
Данный фрагмент кода аналогичен коду выше, следовательно, может быть вынесен в отдельную функцию.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task11.py
> +                girl_top_set.add(g_temp_name)
Два одинаковых фрагмента кода. См. замечание выше.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task11.py
> +                if years in range(1900, 2013):
Начало диапазона должно быть больше 1900, конец - меньше 2012.
Следовательно, `year[0] >= 1900` и `year[1] <= 2012` проверяют, что запрашиваемый диапазон допустим. И при этом нет необоснованного потребления памяти.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task14.py
> +                        raise TooManyErrors(f'Number of attempts exceeded: {numb_try} ')
1. `возникло какое-то исключение, то функция должна перезапуститься еще раз.` - не реализовано.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task2.py
> +    return result_list
Если обратите внимание на пример работы функции в условии, то увидите, что вывод должен быть строкой, а не списком.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task7.py
> +def ordinal_date(day, month, year):
> Программа должна запускаться только в том случае, если она не импортирована в виде модуля в другой файл.

Не реализовано.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task7.py
> +        temporary_month_sum += month_days[elem]
Можно решить с использованием срезов и функции высшего порядка `sum()`.

2022-05-03 15:13 UTC, Shurke commented on src/homework4/task11.py
> +    main()
Почему данная конструкция используется не во всех задачах?

2022-05-09 14:01 UTC, Shurke requested changes

2022-05-09 14:01 UTC, Shurke commented on src/homework4/task11.py
> +    names = get_top_names(names_dict)
Я бы рекомендовал бы здесь полученный кортеж значений распаковывать в понятные переменные.
```py
universal_names, boy_top_names, girl_top_names = get_top_names(names_dict)
```

2022-05-09 14:01 UTC, Shurke commented on src/homework4/task14.py
> +                return func(*args, **kwargs)
Перезапуск функции должен быть внутри блока `for`.  В вашем случае, цикл отсчитает свое количество раз и поднимет `TooManyErrors`. 
Кроме того, при таком при повторном вызове `func` внутри тела цикла может возникнуть исключение, которое надо обработать.

2022-05-09 14:01 UTC, Shurke commented on src/homework4/task14.py
> +                for quant_try in range(1, numb_try + 1):
Повторных вызовов в цикле должно быть на 1 меньше, т.к. в 23-ей строке была уже первая попытка выполнить функцию.

2022-05-09 14:01 UTC, Shurke commented on src/homework4/task9.py
> +    return numb, tool
Для чего нужна это строка?

2022-05-09 20:13 UTC, Kir3103 commented on src/homework4/task14.py
> +                for quant_try in range(1, numb_try + 1):
Если пишу for quant_try in range(1, numb_try) или просто for quant_try in range(numb_try), то возвращается None

2022-05-12 12:27 UTC, Shurke commented
Итоговая оценка - 9.

2022-05-12 12:27 UTC, closed without merging