Homework4: Andrey Senko
Shurke/pt1-47-22 pull request #67
Opened 2022-05-03 17:49 UTC by m4noon

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-05-05 14:38 UTC, Shurke requested changes
Достаточно переменных, имена которых представляют одну букву. Такие имена ничего не говорят о том, что они хранят в себе.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task1.py
> +            log.write(f'Результат вызова функции: {result}\n')
Если файл отсутствует, то открытие файла в режиме "дополнения" создаст файл.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task10.py
> +            pass
А для чего вы создаете файл, если вы должны из него читать?

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task10.py
> +                   'Решение: ')
Ваше решение выходит за рамки условия задачи.
Пожалуйста, следуйте условию.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task11.py
> +def main():
В функциях `find_top_by_one_year` и `find_top_by_range_of_year` можно найти два дублирующихся блока кода: код для нахождения всех данных для мальчиков и точно такой же, но уже для девочек. 
Следовательно, можно выделить общие функции, которые будут принимать в себя пол и возвращать соотвествующие данные.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task11.py
> +    years = years.replace('-', ' ').split()
Метод `split()` может принимать разделитель, по которому будет произведено деление строки.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task11.py
> +    years = [str(i) for i in range(years[0], years[1] + 1)]
Более правильным подходом будет использование генераторного выражения. Это позволит получать значение года в цикле на 100 строке, но при этом не хранить все значения в памяти.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task11.py
> +        for j in i:
Переменные `j` и `i` не несут никакой информации о том, что они содержат.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task11.py
> +        dict_girls[girls_temp[i]] = int(girls_temp[i + 1])
Что мешает сразу по `boys_temp` итерироваться?
```py
for i in boys_temp:

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task12.py
> +    i += 1
Каждый рекурсивный вызов функции `number_converter` будет создавать новый объект функции. Следовательно, `i` будет всегда равняться 1.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task13.py
> +        print(f'Слово {new_word} можно выразить через таблицу элементов Менделеева')
> Отобразите на экране названия элементов вместе с обозначениями, которые были использованы
для их написания. Например, одна из строчек может выглядеть так: Silver может быть представлен как SiLvEr

В условии достаточно подробно описан результат работы функции.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task14.py
> +                except ValueError:
В условии к задаче не сказано ничего о том, какой тип исключения должен быть обработан.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task14.py
> +            for n in range(1, limit + 1):
```py
for n in range(limit):
```
Тоже сработает.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task14.py
> +class TooManyErrors(ValueError):
Пользовательские исключения следует наследовать от `Exception`.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task6.py
> +    print(f'Итоговая сумма оплаты такси: {calc(dist * 10)} BYN')
Умножение на 10 лучше перенести на 18-ю строку. 
Это сделает решение более явным.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task7.py
> +    leap_year = [year for year in range(1900, 2201, 4)]
У високосного года есть явные признаки, по которому можно определить его.
Поэтому, вместо генерирования всех високосных годов, можно воспользоваться проверкой.
Если год високосный, то в `table_of_month` стоит сразу заменить количество дней для февраля.
А не делать это где-то посреди кода.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task7.py
> +                break
Нет никакого смысла в дублировании данного кода.

2022-05-05 14:38 UTC, Shurke commented on src/homework4/task9.py
> +        component['teaspoon'] -= 16
Через целочисленное деление и вычисление остатка от деления решать задачу проще.

2022-05-21 19:13 UTC, m4noon commented on src/homework4/task1.py
> +            log.write(f'Результат вызова функции: {result}\n')
Забыл про это, спасибо.

2022-05-21 19:13 UTC, m4noon commented on src/homework4/task10.py
> +            pass
Думал перестраховаться, удалил.

2022-05-21 19:14 UTC, m4noon commented on src/homework4/task10.py
> +                   'Решение: ')
Хорошо, больше не буду)

2022-05-21 19:17 UTC, m4noon commented on src/homework4/task11.py
> +def main():
Согласен, перенёс данные блоки в функцию `find_top_by_gender`.

2022-05-21 19:17 UTC, m4noon commented on src/homework4/task11.py
> +    years = years.replace('-', ' ').split()
Вылетело из головы, спасибо, исправил.

2022-05-21 19:19 UTC, m4noon commented on src/homework4/task11.py
> +    years = [str(i) for i in range(years[0], years[1] + 1)]
Переделал насколько вас понял.

2022-05-21 19:19 UTC, m4noon commented on src/homework4/task11.py
> +        for j in i:
Исправил.

2022-05-21 19:21 UTC, m4noon commented on src/homework4/task11.py
> +        dict_girls[girls_temp[i]] = int(girls_temp[i + 1])
Тогда у меня ничего не получится.

2022-05-21 19:22 UTC, m4noon commented on src/homework4/task12.py
> +    i += 1
Знаю, так и задумывал.

2022-05-21 19:22 UTC, m4noon commented on src/homework4/task13.py
> +        print(f'Слово {new_word} можно выразить через таблицу элементов Менделеева')
Исправил.

2022-05-21 19:22 UTC, m4noon commented on src/homework4/task14.py
> +                except ValueError:
Исправил.

2022-05-21 19:22 UTC, m4noon commented on src/homework4/task14.py
> +            for n in range(1, limit + 1):
Спасибо, исправил.

2022-05-21 19:23 UTC, m4noon commented on src/homework4/task14.py
> +class TooManyErrors(ValueError):
Исправил.

2022-05-21 19:23 UTC, m4noon commented on src/homework4/task6.py
> +    print(f'Итоговая сумма оплаты такси: {calc(dist * 10)} BYN')
Согласен, исправил.

2022-05-21 19:23 UTC, m4noon commented on src/homework4/task7.py
> +    leap_year = [year for year in range(1900, 2201, 4)]
Согласен, исправил.

2022-05-21 19:24 UTC, m4noon commented on src/homework4/task7.py
> +                break
Увлёкся). Исправил.

2022-05-21 19:25 UTC, m4noon commented on src/homework4/task9.py
> +        component['teaspoon'] -= 16
Может быть, но для меня такой способ решения выглядит более явно.

2022-05-22 11:59 UTC, Shurke requested changes

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +    with open(files[find_year.index(12)], 'rt') as file:
Это скорее придирка, чем замечание.
В коде стоит избегать таких "магических" чисел. Читая такой код, то нет ответа, почему тут `12`. Лучше сохранять число в переменную, имя которой будет нести пояснение, почему такое значение. Либо, можно добавить комментарий, почему именно `12`.
И в целом, ниже по коду, тоже имеются какие-то "магические" числа.

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +        print(f'Универсальные имена: {universal_names}')
У меня возникает вопрос, почему вывод универсальных имен сделан внутри этой функции, но отдельные топ-10 возвращаются и выводятся на экран в рамках `main()`?

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +    files = read_zip()
Прежде чем начинать работу скрипта стоило бы проверить, а правильные ли данные ввел пользователь.

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +              f'Список популярных имён для девочек: {top_girls}')
Если вы уже начали задумываться о красивом выводе, то стоило бы еще добавить информацию о том, за какой год выводится топ.

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +    for v in sorted_keys:
Что значит `v`?

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +        list_of_names.append(k)
Что значит `k`?

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +            girls.append(girl)
А почему не использовали list comprehension для формирования `boys, girls и universal_names`?

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task11.py
> +    top_girls = temp_girls[:10]
Эта часть кода также содержится в функции `find_top_by_one_year`.  
Не вижу смысла в таком дублировании кода, когда очень просто выносится в отдельную функцию.

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task6.py
> +    price = basic + round(cost * dist * 10, 2)
Для чего используете округление?

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task7.py
> +    if month in range(1, 10):
```py
if month <= 10:
```
И тогда можно избежать создание генератора, тем самым заняв меньше памяти.

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task7.py
> +        table_of_month['02'] = 29
Условие вычисления високосного года чуть более сложное, чем просто кратное 4-м. 
Годы, номер которых кратен 100, — невисокосные (например, годы 1700, 1800, 1900, 2100, 2200, 2300). При этом, они попадают в вашу выборку.

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task7.py
> +    for k, v in table_of_month.items():
`k, v` - ужасные имена переменных.

2022-05-22 11:59 UTC, Shurke commented on src/homework4/task7.py
> +    year = int(input('Введите год: '))
А почему бы не принимать у пользователя дату в формате `dd.mm.yyyy` или `dd/mm/yyyy`?

2022-05-30 17:59 UTC, m4noon commented on src/homework4/task11.py
> +    with open(files[find_year.index(12)], 'rt') as file:
Да, согласен с вами. Постарался переделать эти моменты, чтобы код стал яснее.

2022-05-30 18:03 UTC, m4noon commented on src/homework4/task11.py
> +        print(f'Универсальные имена: {universal_names}')
Этот вывод делался почти в конце выполнения таска, и тогда не подумал, что этому выводу действительно тут не место. Исправил.

2022-05-30 18:03 UTC, m4noon commented on src/homework4/task11.py
> +    files = read_zip()
Согласен, исправил.

2022-05-30 18:06 UTC, m4noon commented on src/homework4/task11.py
> +              f'Список популярных имён для девочек: {top_girls}')
Добавил за какой год выводится информация если пользователь не ввёл никакого года, в иных случаях пользователь сам вводит за какой год ему показать информацию, поэтому за один год и за период не стал добавлять это.

2022-05-30 18:08 UTC, m4noon commented on src/homework4/task11.py
> +    for v in sorted_keys:
Каюсь, привык писать "по-быстрому" key и value сокращённо (k и v), когда работаю со словарями. Исправил.

2022-05-30 18:08 UTC, m4noon commented on src/homework4/task11.py
> +        list_of_names.append(k)
Каюсь, привык писать "по-быстрому" value сокращённо (v), когда работаю со словарями. Исправил.

2022-05-30 18:11 UTC, m4noon commented on src/homework4/task11.py
> +            girls.append(girl)
Когда писал код думал  больше о логике, поэтому изначально начал так писать, а потом что-то не вспомнил что можно сократить код используя list comprehension. Спасибо что напомнили. Переделал.

2022-05-30 18:12 UTC, m4noon commented on src/homework4/task11.py
> +    top_girls = temp_girls[:10]
Согласен с вами, вынес в новую функцию `find_top`.

2022-05-30 18:18 UTC, m4noon commented on src/homework4/task6.py
> +    price = basic + round(cost * dist * 10, 2)
Думал если пользователь вдруг впишет километры в целой части, и метры в дробной (5.13 к примеру) , то при расчёте может получиться 3 значащих числа копеек (.xxx). Убрал округление.

2022-05-30 18:18 UTC, m4noon commented on src/homework4/task7.py
> +    if month in range(1, 10):
Да, так явно лучше, спасибо. Исправил.

2022-05-30 18:19 UTC, m4noon commented on src/homework4/task7.py
> +        table_of_month['02'] = 29
Да, не учёл в прошлый раз это, спасибо. Исправил.

2022-05-30 18:20 UTC, m4noon commented on src/homework4/task7.py
> +    for k, v in table_of_month.items():
Больше не буду так писать). Исправил.

2022-05-30 18:20 UTC, m4noon commented on src/homework4/task7.py
> +    year = int(input('Введите год: '))
Спасибо за идею. Исправил на данный формат.

2022-06-19 17:19 UTC, Shurke commented
Итоговая оценка - 8.

2022-06-19 17:19 UTC, closed without merging