Homework4:Bakacheuski Dmitry
Shurke/pt1-47-22 pull request #69
Opened 2022-05-04 22:02 UTC by DmitryBakacheuski

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-05-17 14:44 UTC, Shurke requested changes

2022-05-17 14:44 UTC, Shurke commented on src/task10.py
> +            len_word = len(i)
Здесь можно применить агрегирующую функцию `max()`.

2022-05-17 14:44 UTC, Shurke commented on src/task1.py
> +    i = [x for x in range(number ** degree) if x % 2 == 0]
Все же лучше использовать вместо `i` имя переменной `result`.

2022-05-17 14:44 UTC, Shurke commented on src/task11.py
> +                if num_of_year in range(1900, 2013):
В общем случае, то сначала проверяют валидность данных, а только потом начинают осуществлять вычисления.

2022-05-17 14:44 UTC, Shurke commented on src/task11.py
> +def top_10_names(year):
В коде данной функции имеется два повторяющихся блока: для имен мальчиков и для имен девочек. Можно сделать более общую функцию и вызывать ее, подставляя желаемый пол.

2022-05-17 14:44 UTC, Shurke commented on src/task12.py
> +def roman_numer(number):
Функция не является рекурсивной.

> Создайте рекурсивную функцию, которая будет переводить римскую запись чисел в десятичную.

2022-05-17 14:44 UTC, Shurke commented on src/task12.py
> +    print(f'{roman_input} в десятичной системе исчисления будет: {roman_numer(roman_input)}')
Почему данная конструкция не применяется в задачах 1, 10, 11?

2022-05-17 14:44 UTC, Shurke commented on src/task13.py
> +    print(f'Введенное слово из названий химических элементов: {decompose(word, list_elements)}')
Формировать возвращаемый результат все же стоит в функции `decompose`. 
Потому что сейчас вполне возможен следующий вывод `Введенное слово из названий химических элементов: Не возможно собрать данное слово из элементов таблицы Менделеева!`

2022-05-17 14:44 UTC, Shurke commented on src/task14.py
> +            except ValueError:
В условии задачи ничего не сказано, что только `ValueError` должно обрабатываться.

2022-05-17 14:44 UTC, Shurke commented on src/task14.py
> +                    return wrapper(*args, **kwargs)
Почему возвращается результат вызова `wrapper`?

2022-05-17 14:44 UTC, Shurke commented on src/task14.py
> +                func(*args, **kwargs)
Как вы планируете возвращать результат работы `func`?

2022-05-17 14:44 UTC, Shurke commented on src/task14.py
> +            return func
Для чего вы возвращаете `func`?

2022-05-17 14:44 UTC, Shurke commented on src/task7.py
> +    main()
Если вы используете данный подход, то используйте во всех файлах домашки.

2022-05-17 14:44 UTC, Shurke commented on src/task3.py
> +def func_1(number_to_binary):
А что помешало дать нормальные имена функциям?

2022-05-17 14:44 UTC, Shurke commented on src/task4.py
> +    print('Ближайшую степень двойки к введенному числу', (2 ** PREVIOUS))
Почему решение не помещено в функцию?

2022-05-17 14:44 UTC, Shurke commented on src/task5.py
> +print(f'Максимальный делитель введенного числа являющийся степенью двойки: {i}')
Почему решение не помещено в функцию?

2022-05-17 14:44 UTC, Shurke commented on src/task7.py
> +    if year % 4 == 0 != year % 100 or year % 400 == 0:
После установления, что год високосный, достаточно обновить значение в словаре `dict_days` для 2 месяца. Тогда не нужно будет использовать тот костыль, что на 22-23 строках.

2022-05-17 14:44 UTC, Shurke commented on src/task9.py
> +input_number = int(input("Введите количество единиц измерения: "))
В условии задачи есть пример ввода `59 чайных ложек`.
Обрабатывайте ввод с помощью одного запроса.

2022-05-22 12:08 UTC, Shurke requested changes

2022-05-22 12:08 UTC, Shurke commented on src/task11.py
> +                if num_of_year in range(1900, 2013):
Не исправлено.

2022-05-22 12:08 UTC, Shurke commented on src/task11.py
> +                    top_10_names(num_of_year)
При таком подходе, вы будете возвращать топ-10 за каждый год в введенном интервале.
На мой взгляд, как пользователя, ожидаю сразу же обобщенный список за все года интервала.

2022-05-22 12:08 UTC, Shurke commented on src/task11.py
> +def top_10_names(year):
Не исправлено.

2022-05-22 12:08 UTC, Shurke commented on src/task12.py
> +    print(f'{roman_input} в десятичной системе исчисления будет: {roman_numer(roman_input)}')
Не исправлено.

2022-05-22 12:08 UTC, Shurke commented on src/task4.py
> +    find_degree(input_number)
Почему такая конструкция не добавлена в `task3`?

2022-05-22 12:08 UTC, Shurke commented on src/task5.py
> +input_number = int(input('Введите число: '))
16 и 17 строку стоит поменять местами.

2022-05-22 12:08 UTC, Shurke commented on src/task7.py
> +                     11: 305, 12: 335}
Достаточно было бы обновить значение, которое находится по ключу `3`
```py
dict_days[3] = 60
```

2022-05-22 12:08 UTC, Shurke commented on src/task7.py
> +    main()
Все еще актуально.

2022-05-24 17:36 UTC, DmitryBakacheuski commented on src/task11.py
> +                if num_of_year in range(1900, 2013):
Я думал что нужно выводить результаты за каждый год отдельно, такое решение подходило

2022-05-24 17:36 UTC, DmitryBakacheuski commented on src/task11.py
> +def top_10_names(year):
Сложная задачка, видимо запарился со всеми исправлениями из забыл о втором блоке

2022-05-24 17:37 UTC, DmitryBakacheuski commented on src/task11.py
> +                    top_10_names(num_of_year)
Возможно костыльно но переделал ответы для интервалов

2022-05-24 17:44 UTC, DmitryBakacheuski commented on src/task12.py
> +    print(f'{roman_input} в десятичной системе исчисления будет: {roman_numer(roman_input)}')
Не думал что это обязательный критерий

2022-05-24 17:45 UTC, DmitryBakacheuski commented on src/task4.py
> +    find_degree(input_number)
Не знал что это обязательно

2022-05-24 17:47 UTC, DmitryBakacheuski commented on src/task5.py
> +input_number = int(input('Введите число: '))
Видимо порадовался что все работает и пропустил

2022-05-24 17:48 UTC, DmitryBakacheuski commented on src/task7.py
> +                     11: 305, 12: 335}
Такое действие повлияет только на март, на остальные месяцы не распространится такое обновление

2022-05-24 17:49 UTC, DmitryBakacheuski commented on src/task7.py
> +    main()
Вроде  поправил

2022-06-19 17:15 UTC, Shurke commented on src/task7.py
> +                     11: 305, 12: 335}
Справедливо.

2022-06-19 17:15 UTC, Shurke commented
Итоговая оценка - 8.

2022-06-19 17:15 UTC, closed without merging