Homework 5
Shurke/pt1-47-22 pull request #70
Opened 2022-05-07 12:02 UTC by Jenderlion

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle).
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks.
- [x] my PR made from the fork feature branch to appropriate branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-05-22 13:02 UTC, Shurke requested changes

2022-05-22 13:02 UTC, Shurke commented on src/task4.py
> +        result_list = Primes()
Для чего нужно здесь создавать экземпляр Primes?

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task1.py
> +        self.task = task1.KgToPounds
Более явно было бы что-то в виде `converter`.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task1.py
> +        self.assertEqual(test_object.kg, value)
Не самая лучшая идея, устанавливать и потом с этим же числом сравнивать.
Более правильно будет задать `expected_value`.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task2.py
> +    def test_compare(self, str_1, str_2, str_2_is_realstring, compare, check):
В этом тесте смешались в кучу "кони, люди и залпы тысячи орудий".
Стоит написать тесты, которые отдельно тестируют каждую операцию сравнения. 
При текущем подходе, если упадет тест 'greater than', то мы уже не протестируем 'less than'.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task3.py
> +        self.assertEqual(object_1, object_2)
В данном случае стоит использовать метод [assertIs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIs).

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task3.py
> +                return 'You are very cool!'
Вспомогательные методы и классы не должны быть определены в тесте.
Стоит вынести из теста.
Второе, нет необходимости в добавлении какой-то логики. Следовательно, `some_business_method` и `some_other_business_method` можно и нужно удалить.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task4.py
> +    """Test cases for RealString"""
Копипаста. :)

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task4.py
> +            result_list = self.task.first(right_limit)
Методы `first` и `last` стоит тестировать отдельными тестами.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task5.py
> +    """Test cases for RealString"""
Копипаста. :)

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task5.py
> +    def test_class(self, seq, default_value, attr, attr_val, index, check_value):
Здесь также должно быть 2 теста:
1. тестирует, что весь функционал list работает, как и должен;
2. проверка работы возврата default value.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task6.py
> +Unittest for task5.py
1. Неправильная строка документации.
2. Если в этом файле планируется тестировать старые домашние работы, то имя файла об этом должно сообщать.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task6.py
> +        self.task13_file = task13.get_chem_elements_from_file
Если в этом файле тестируются все функции из "старой" домашней работы, то это должны быть отдельные тестовые классы. Т.к. каждая домашка - это отдельный функционал, который никак не связан с другой.

2022-05-22 13:02 UTC, Shurke commented on src/tests/test_task6.py
> +        """Test Task2.py with data {0} and expected value {1}"""
Строка документации просто для того, что бы быть.
Ни что тестируется, ни зачем.
Стоит пересмотреть лекцию по Django, где шел разговор о тестах.

2022-05-25 13:59 UTC, Jenderlion commented on src/task4.py
> +        result_list = Primes()
Т.к. по условию вызов метода выглядит как "Primes.first(20).last(5)", метод first() должен возвращать экземпляр класса Primes.

2022-05-25 14:00 UTC, Jenderlion commented on src/tests/test_task1.py
> +        self.task = task1.KgToPounds
Исправлено.

2022-05-25 14:00 UTC, Jenderlion commented on src/tests/test_task5.py
> +    def test_class(self, seq, default_value, attr, attr_val, index, check_value):
Исправлено.

2022-05-25 14:00 UTC, Jenderlion commented on src/tests/test_task1.py
> +        self.assertEqual(test_object.kg, value)
Исправлено.

2022-05-25 14:01 UTC, Jenderlion commented on src/tests/test_task2.py
> +    def test_compare(self, str_1, str_2, str_2_is_realstring, compare, check):
Разбил тесты.

2022-05-25 14:01 UTC, Jenderlion commented on src/tests/test_task5.py
> +    """Test cases for RealString"""
Исправлено.

2022-05-25 14:01 UTC, Jenderlion commented on src/tests/test_task4.py
> +            result_list = self.task.first(right_limit)
Исправлено.

2022-05-25 14:01 UTC, Jenderlion commented on src/tests/test_task3.py
> +        self.assertEqual(object_1, object_2)
Исправлено.

2022-05-25 14:02 UTC, Jenderlion commented on src/tests/test_task3.py
> +                return 'You are very cool!'
Вынес вспомогательный класс из тестового класса.
Логику добавил из-за жалоб пайлинта.

2022-05-25 14:02 UTC, Jenderlion commented on src/tests/test_task4.py
> +    """Test cases for RealString"""
Исправлено.

2022-05-25 14:03 UTC, Jenderlion commented on src/tests/test_task6.py
> +Unittest for task5.py
Исправлено.

2022-05-25 14:03 UTC, Jenderlion commented on src/tests/test_task6.py
> +        self.task13_file = task13.get_chem_elements_from_file
Исправлено.

2022-05-25 14:04 UTC, Jenderlion commented on src/tests/test_task6.py
> +        """Test Task2.py with data {0} and expected value {1}"""
Исправлено.

2022-06-19 17:11 UTC, Shurke requested changes

2022-06-19 17:11 UTC, Shurke commented on src/task2.py
> +            result = NotImplemented
При таком подходе лучше бы райзить `TypeError`, как делает это интерпретатор.

2022-06-19 17:11 UTC, Shurke commented on src/task3.py
> +        return 'You are very cool!'
А зачем оно тут?

2022-06-19 17:11 UTC, Shurke commented on src/task4.py
> +        result_list = Primes()
Метод `first()` возвращает список чисел, а не экземпляр класса.)

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task1.py
> +        self.converter = task1.KgToPounds
А что помешало сразу в коде использовать `task1.KgToPounds`? (замечание в целом применимо и к другим тестам)

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task1.py
> +    def test_to_pounds_positive(self, kg, pounds):
А негативные сценарии?

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task1.py
> +class TestTask1(unittest.TestCase):
Не хватает теста, который проверит правильность создания экземпляра класса `KgToPounds`?

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task2.py
> +class TestTask2(unittest.TestCase):
Не хватает негативных сценариев.

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task3.py
> +        return 'You are very cool!'
Для чего эти методы нужны?

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task4.py
> +        (5, [2, 3, 5, 7, 11]),
А если на вход подать 0 или отрицательно число?

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task4.py
> +        (20, 5, [53, 59, 61, 67, 71])
А если на вход подать 0 или отрицательно число?

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task5.py
> +        self.default_list = task5.DefaultList
Если уже так хочется что-то в setUp создать, то делать это нужно с пользой.
```py
self.default_list = task5.DefaultList((1, 2, 3), 'def_val')
```
`1, 2, 3)` и `'def_val'` встречаются во всех тестах при создании экземпляра `DefaultList`. Так почему тогда сразу в `setUp` не создать такой вариант?

2022-06-19 17:11 UTC, Shurke commented on src/tests/test_task6(tasks_from_hw5).py
> +        Tests the conversions sequences to ranges
Что мешало написать нормальную строку документации?
Ведь тестируется не просто превращение последовательности в диапазон, а сворачивание чисел в интервалы.

2022-06-26 10:52 UTC, Jenderlion commented on src/task2.py
> +            result = NotImplemented
Исправлено

2022-06-26 10:53 UTC, Jenderlion commented on src/task3.py
> +        return 'You are very cool!'
Pylint требует наличия нескольких методов в классе, иначе не пропускает код

2022-06-26 11:05 UTC, Jenderlion commented on src/tests/test_task1.py
> +class TestTask1(unittest.TestCase):
Добавлено

2022-06-26 11:05 UTC, Jenderlion commented on src/tests/test_task3.py
> +        return 'You are very cool!'
Требование Pylint'a

2022-06-26 11:09 UTC, Jenderlion commented on src/tests/test_task4.py
> +        (5, [2, 3, 5, 7, 11]),
Добавил в тест

2022-06-26 11:09 UTC, Jenderlion commented on src/tests/test_task4.py
> +        (20, 5, [53, 59, 61, 67, 71])
Добавил в тест и изменил логику работы метода

2022-06-26 11:13 UTC, Jenderlion commented on src/tests/test_task5.py
> +        self.default_list = task5.DefaultList
Реализовал

2022-06-26 11:19 UTC, Jenderlion commented on src/tests/test_task6(tasks_from_hw5).py
> +        Tests the conversions sequences to ranges
Исправил для всех тестов

2022-06-26 11:35 UTC, Jenderlion commented on src/tests/test_task1.py
> +    def test_to_pounds_positive(self, kg, pounds):
Добавил негативные сценарии

2022-06-26 15:24 UTC, Jenderlion commented on src/tests/test_task2.py
> +class TestTask2(unittest.TestCase):
Добавлено

2022-06-30 15:06 UTC, Shurke commented
Итоговая оценка - 8.

2022-06-30 15:06 UTC, closed without merging