Homework4: Molchanov Artem
Shurke/pt1-47-22 pull request #71
Opened 2022-06-01 12:23 UTC by Kissloroid

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-06-19 16:45 UTC, Shurke requested changes
1. В функциях пропущены строки документации.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task01.py
> +    counters = {}
При таком подходе, результат работы функции будет будет храниться только на протяжении работы интерпретатора. А условие задачи говорит про "за все время вызова".

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task02.py
> +            )
Это красивая конструкция, но в реальной жизни лучше избегать их, т.к. сложно понимать такую штуку.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task03.py
> +def binary_pyramid(start, finish):
Где строка документации?

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task02.py
> +    def get_list(ls):
Где строки документации?

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task07.py
> +    print(ordinal_date(day, month, year))
Почему данная конструкция применяется только в этом задании, а в других - нет?

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task09.py
> +quan = int(input("Введите количество: "))
Необходимые данные легко принимать из одной строки.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +        if 2013 < start_year or start_year < 1900:
Для чего здесь обрабатывать 2 переменные?
Если все дело в функции `get_result`, то там можно `finish_year` сделать необязательным аргументом.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +    elif len(period) == 0:
По идее, тут все же стоит `else` использовать.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +    dict_top = {x[0]: x[1] for x in result_list[:10]}
Мягко говоря очень неудачный пример нейминга:
`x[0] и x[1]` ничего не говорят о том, что тут хранится.
`result_list` - что это за структура, какие в ней данные?

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +        for itm in full_list:
Для чего дважды итерироваться по одному и тому объекту?

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +    sorted_keys = sorted(temp_result, key=temp_result.get, reverse=True)
Еще один пример неудачного именования переменных.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +                list_for_set.append(i.rstrip().split())
Нельзя ли обойтись одним чтением из файла за всю работу программы?
Т.е. вычитать данные, а потом уже их обрабатывать их.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +def get_list_for_set(start_year, finish_year, gender):
`get_universal_names` выглядит более удачным именем функции.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task11.py
> +"""
В целом, в этой задаче очень плохо с именованием переменных. Стоит пересмотреть подход к именованию переменных.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task12.py
> +def from_roman(input_number):
Функция не является рекурсивной.
Из условия

> Создайте рекурсивную функцию...

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task13.py
> +def matching_with_elements(word, elem_list, result=[]):
Я на лекции обращал внимание на то, как создавать функцию, когда нужно иметь в качестве дефолтного значения изменяемый объект.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task13.py
> +        return ''.join(result)
Интересное конечно решение, использовать таким образом изменяемый объект в рекурсивной функции. Такой подход может привести к ошибкам во время работы программы. И я бы рекомендовал использовать более явный подход.

2022-06-19 16:45 UTC, Shurke commented on src/Homework4/task13.py
> +    elements_list = elements[1::2]
Более правильно будет вычитывать строку за строкой в файле и сразу же обрабатывать вычитанное значение, подготавливая таким образом данные к последующей работе.
У вас же в памяти и `elements` и его копия `elements_list`.

2022-06-22 22:20 UTC, Kissloroid commented on src/Homework4/task03.py
> +def binary_pyramid(start, finish):
Принято.

2022-06-22 22:20 UTC, Kissloroid commented on src/Homework4/task02.py
> +    def get_list(ls):
Принято.

2022-06-22 22:40 UTC, Kissloroid commented on src/Homework4/task07.py
> +    print(ordinal_date(day, month, year))
Не совсем понимаю, о чём речь?

2022-06-22 22:41 UTC, Kissloroid commented on src/Homework4/task11.py
> +"""
Принято

2022-06-22 22:42 UTC, Kissloroid commented on src/Homework4/task12.py
> +def from_roman(input_number):
Принято

2022-06-22 22:50 UTC, Kissloroid commented on src/Homework4/task13.py
> +def matching_with_elements(word, elem_list, result=[]):
Я не совсем понял, о чём идёт речь? Как мне кажется вы имеете ввиду, что result=[] не может находится в аргументах функции, верно?

2022-06-22 22:53 UTC, Kissloroid commented on src/Homework4/task13.py
> +    elements_list = elements[1::2]
Я вас понял. Значит нужно полностью задачу переделывать, мне казалось по неопытности, что неплохо подошёл к вопросу :)

2022-06-22 22:59 UTC, Kissloroid commented on src/Homework4/task02.py
> +            )
Такое решение мне показалось более универсальным, я долго думал над этой задачей, в результате пошёл искать помощи в сети. В результате нашёл что-то похожее, но на java, переписал под python.

2022-06-22 23:35 UTC, Kissloroid commented on src/Homework4/task09.py
> +quan = int(input("Введите количество: "))
Подумал, что со стороны пользователя это будет наглядней

2022-06-22 23:38 UTC, Kissloroid commented on src/Homework4/task11.py
> +    elif len(period) == 0:
Видимо так

2022-06-22 23:48 UTC, Kissloroid commented on src/Homework4/task11.py
> +        for itm in full_list:
Моя логика была следующей: при формировании топ 10 за несколько лет некоторые имена могли меняться местами с 5е на 7е к примеру в зависимости от количества названных совпадающих имён в 87м году и в 88м. И составлять топ уже по большей цифре.

2022-06-22 23:50 UTC, Kissloroid commented on src/Homework4/task11.py
> +                list_for_set.append(i.rstrip().split())
Данный момент был именно пот той же причине реализован. Возможно переборщил с задуманной идеей правильного топ10

2022-06-25 08:57 UTC, Shurke commented on src/Homework4/task02.py
> +            )
В целом, чем проще написан код - тем лучше.)

2022-06-25 08:57 UTC, Shurke commented on src/Homework4/task07.py
> +    print(ordinal_date(day, month, year))
Речь шла о конструкции `if __name__ == "__main__"`.

2022-06-25 08:57 UTC, Shurke commented on src/Homework4/task13.py
> +def matching_with_elements(word, elem_list, result=[]):
При нескольких вызовах `matching_with_elements`, каждый раз `result`  будет становиться пустым списком. Тем самым может привести к неприятным багам.
Если нужно изменяемый объект иметь как значение по умолчанию, то следует использовать следующий подход
```py
def matching_with_elements(word, elem_list, result=None):
    result = [] if result is None else result
```

2022-06-25 08:57 UTC, Shurke commented on src/Homework4/task01.py
> +    counters = {}
Не исправлено.

2022-06-25 08:57 UTC, Shurke commented
Итоговая оценка - 7.5

2022-06-25 08:57 UTC, closed without merging