Homework 5: Kiryl Strunets
Shurke/pt1-47-22 pull request #72
Opened 2022-06-06 10:38 UTC by Kir3103

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2022-06-19 14:14 UTC, Shurke requested changes

2022-06-19 14:14 UTC, Shurke commented on src/homework5/task1.py
> +class KgToPounds:
Решение очень похоже на решение [Tatsiana Sauko](https://github.com/Shurke/pt1-47-22/pull/73/files#).

2022-06-19 14:14 UTC, Shurke commented on src/homework5/task1.py
> +            raise ValueError('Килограммы задаются только числами')
Выглядит очень странным текст на русском, когда чуть выше сообщение об ошибке написано на английском.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/task1.py
> +        if isinstance(self.__kg, (int, float)):
Эту проверку стоит вынести в `__init__`, чтобы экземпляр класса всегда создавался только с допустим значением. Тогда проверка в момент конвертации уже будет не нужна.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/task3.py
> +        return instance
При таком подходе, вместо желаемого экземпляра класса, будет возвращен словарь, в котором лежат экземпляры классов.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task1.py
> +        self.kg_to_pounds = task1.KgToPounds
Для чего вы создаете переменную? Что помешало в тесте сразу вызывать `KgToPounds`?

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task1.py
> +        """Test case for kg method with kg={0} and expected_kg {1}"""
У класса `KgToPounds` нет метода `kg`. Вы тестируете сеттер, о чем и следует писать.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task1.py
> +        (4, 4)
Почему нет значений, которые приведут к ошибке?

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task1.py
> +class TestKgToPounds(unittest.TestCase):
Не хватает теста, что класс будет создан правильно. И хранимое значение в классе совпадает с тем, что было передано.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task13_from_hw4.py
> +        ('silicon', None, False),
А в чем разница между этими наборами тестовых данных? Выглядит странно, что в одном случае слово будет представлено из химических элементов, а в другом случае нет.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task13_from_hw4.py
> +         'silicon', False),
Тот же вопрос.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task13_from_hw4.py
> +        result = self.word(word, self.opn()) == res_value
Вызов метода `self.opn()` завязано на наличие файла `elements.txt`, которого в пулл реквесте нет. Следовательно, будь тут CI или кто-то запустит тест локально, работать ничего не будет.

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task2.py
> +        str_to_compare = self.real_str(str_1).__eq__(str_2)
А почему не используется оператор `==`?

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task4.py
> +        (5, [2, 3, 4, 5, 6], False)
А что будет если 0 или отрицательное число передать?

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task4.py
> +        (20, 5, [54, 55, 56, 57, 58], False)
А что будет если 0 или отрицательное число передать?

2022-06-19 14:14 UTC, Shurke commented on src/homework5/tests/test_task9_from_hw4.py
> +        ('cup', 6, '0 cup, 3 tablespoons, 3 teaspoons', False),
Почему у вас на одном тестовом наборе данных получается 2 разных ответа?

2022-06-19 14:20 UTC, Kir3103 commented on src/homework5/task1.py
> +class KgToPounds:
Не могу ничего сказать. Мой PR был открыт намного раньше

2022-06-20 09:43 UTC, Kir3103 commented on src/homework5/tests/test_task1.py
> +        self.kg_to_pounds = task1.KgToPounds
Делал согласно примеру из лекции.
![image](https://user-images.githubusercontent.com/99246188/174571578-f41ac472-4665-4bc3-be93-5b6bf9fec606.png)

Исправлено с учетом замечания

2022-06-20 09:52 UTC, Kir3103 commented on src/homework5/tests/test_task13_from_hw4.py
> +        ('silicon', None, False),
В функции chemistry_word идет проверка, можно ли представить слово с помощью химических элементов и если нельзя, то возвращается None.
Следовательно я проверяю, что с одним и тем же входным набором данных (silicon) функция в первом случае отрабатывает правильно (передает silicon в функцию chemistry_output и ожидаемый результат True), а во втором случае выдает None, что является неправильным результатом (False).

2022-06-20 09:57 UTC, Kir3103 commented on src/homework5/tests/test_task13_from_hw4.py
> +         'silicon', False),
В функции chemistry_output идет вывод сообщения о том, можно ли представить слово в виде химических элементов.
Следовательно я проверяю, что с одним и тем же входным набором данных (silicon) функция в первом случае отрабатывает правильно (выводит положительное сообщение и ожидаемый результат True), а во втором случае выводит сообщение о том, что нельзя представить слово silicon в виде химических элементов, что является неправильным результатом (False).

2022-06-20 10:04 UTC, Kir3103 commented on src/homework5/tests/test_task13_from_hw4.py
> +        result = self.word(word, self.opn()) == res_value
Исправлено. Файл elements.txt добавлен в директорию домашнего задания

2022-06-20 10:13 UTC, Kir3103 commented on src/homework5/tests/test_task2.py
> +        str_to_compare = self.real_str(str_1).__eq__(str_2)
Исправлено.

2022-06-20 10:14 UTC, Kir3103 commented on src/homework5/task1.py
> +            raise ValueError('Килограммы задаются только числами')
Исправлено

2022-06-20 10:18 UTC, Kir3103 commented on src/homework5/task3.py
> +        return instance
Исправлено.

2022-06-20 10:26 UTC, Kir3103 commented on src/homework5/tests/test_task1.py
> +        """Test case for kg method with kg={0} and expected_kg {1}"""
Исправлено

2022-06-20 12:20 UTC, Kir3103 commented on src/homework5/tests/test_task9_from_hw4.py
> +        ('cup', 6, '0 cup, 3 tablespoons, 3 teaspoons', False),
Идет проверка, что с одним и тем же входным набором данных (cup) функция в первом случае отрабатывает правильно и выводит минимальное количество инструментов для использования (6 cup) с ожидаемым результатом True, а во втором случае выводит выводит неправильное количество инструментов для использования (0 cup, 3 tablespoons, 3 teaspoons), о чем говорит ожидаемый результат (False). Соответственно функция kitchen работает правильно.

2022-06-20 13:53 UTC, Kir3103 commented on src/homework5/task1.py
> +        if isinstance(self.__kg, (int, float)):
Исправлено

2022-06-20 19:01 UTC, Kir3103 commented on src/homework5/tests/test_task1.py
> +        (4, 4)
Исправлено

2022-06-20 19:18 UTC, Kir3103 commented on src/homework5/tests/test_task4.py
> +        (5, [2, 3, 4, 5, 6], False)
Исправлено

2022-06-20 19:18 UTC, Kir3103 commented on src/homework5/tests/test_task4.py
> +        (20, 5, [54, 55, 56, 57, 58], False)
Исправлено

2022-06-22 15:56 UTC, Shurke requested changes

2022-06-22 15:56 UTC, Shurke commented on src/homework5/task1.py
> +class KgToPounds:
В ТГ разобрались с этим.

2022-06-22 15:56 UTC, Shurke commented on src/homework5/task1.py
> +        self.__kg = new_kg
Здесь все же стоит оставить проверку, чтобы не было возможности задать неправильное значение.

2022-06-22 15:56 UTC, Shurke commented on src/homework5/tests/test_task1.py
> +        self.kg_to_pounds = task1.KgToPounds
Справедливо.)

2022-06-22 15:56 UTC, Shurke commented on src/homework5/tests/test_task9_from_hw4.py
> +        ('cup', 6, '0 cup, 3 tablespoons, 3 teaspoons', False),
Это очень неявный подход и очень сложен для быстрого понимания.
Кроме того, вы можете сразу сравнивать `result` с `min_actions` в методе `assertEqual`.  Это в целом применимо и к другим тестам.

2022-06-30 15:06 UTC, Shurke commented
Итоговая оценка - 8.

2022-06-30 15:06 UTC, closed without merging